parameters:
    # oro_entity_pagination.example.class: Oro\Bundle\EntityPaginationBundle\Example

services:
    # oro_entity_pagination.example:
    # class: %oro_entity_pagination.example.class%
    # arguments: [@service_id, "plain_value", %parameter%]

